---
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: 0755

- name: Create directory for Node Exporter
  file:
    path: /opt/node_exporter
    state: directory
    mode: 0755

- name: Create Node Exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    createhome: no

- name: Unarchive Node Exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/opt/node_exporter"
    remote_src: yes
    creates: "/opt/node_exporter/node_exporter"

- name: Create systemd service file for Node Exporter
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
